
server {
    listen 80;
    
    # Always return the index.html
    location / {
        root /usr/share/nginx/html;
        add_header Content-Type text/html;
        return 200 '<!DOCTYPE html><html><head><title>TEST NGINX APP 3</title></head><body><h1>HAPPY NEW YEAR 2026! DAY 0 </h1></body></html>';
    }
}